### GET STOCK BY USER ID

GET http://localhost:3003/stock/get
Content-Type: application/json

{
    "user_id": "1"
}

### SEND STOCK DATA TO DB

POST http://localhost:3003/stock/send
Content-Type: application/json

{
    "user_id": "3",
    "resource_number": "12312312",
    "building_material_number": "1231",
    "crafting_material_number": "6456"
}